### ISSUE TITLE
Message Display

### ISSUE THREAD

**Issue by Elyniss** [WalletConnect/web3inbox#185] opened 2023-07-28 12:22 UTC
Messages in widget are displayed in wrong order, and have wrong times

Widget:
![Screenshot 2023-07-28 at 14 10 53](https://github.com/WalletConnect/web3inbox/assets/23137643/3a298d94-4bcb-4bd8-b6a3-bdbc6394a04b)

Ideal state:
![IMG_8AE19E4A2471-1](https://github.com/WalletConnect/web3inbox/assets/23137643/fd93500c-6d9b-4695-ad61-eebb1734412e)

**Comment by devceline** [comment] 2023-08-21 07:12
Duplicate of https://github.com/WalletConnect/web3inbox/issues/196#issue-1846346831

**Closed by devceline** 2023-08-21 07:12 UTC
Labels: bug
