### ISSUE TITLE
P2: Unsubscribing, toast appears and modal dismisses BEFORE sub is removed from the list

### ISSUE THREAD

**Issue by chris13524** [WalletConnect/web3inbox#283] opened 2023-11-22 13:40 UTC

**Comment by chadyj** [comment] 2024-01-11 20:08
I think this is a dupe of https://github.com/WalletConnect/web3inbox/issues/380
This one was first, but the other has more info, so closing this one.
@chadyj Please re-open if this is a separate issue.

**Closed by chadyj** 2024-01-11 20:08 UTC
